# Generated by Django 5.2.14 on 2026-05-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Categoria')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=120, unique=True, verbose_name='Número do Processo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Classe')),
                ('descricao', models.CharField(blank=True, max_length=180, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='classes', to='empenhos.categoria')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('valor_informado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Informado')),
                ('valor_empenhado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Empenhado')),
                ('data_lancamento', models.DateField(blank=True, null=True, verbose_name='Data do Lançamento')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Usuário/Observação')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empenhos.categoria')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empenhos.classe')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='empenhos.processo')),
            ],
            options={
                'verbose_name': 'Lançamento de Empenho',
                'verbose_name_plural': 'Lançamentos de Empenhos',
                'ordering': ['-ano', '-mes', 'classe__codigo', 'processo__numero'],
            },
        ),
    ]
