# Generated by Django 5.2.14 on 2026-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='ano_referencia',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_informado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
