# Generated by Django 5.2.14 on 2026-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empenhos', '0002_processo_ano_referencia_processo_valor_informado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentoempenho',
            name='valor_informado',
        ),
    ]
