# Generated by Django 5.2.14 on 2026-05-16 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenhos', '0003_remove_lancamentoempenho_valor_informado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='valor_informado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor Informado'),
        ),
    ]
